### ISSUE TITLE
Planing

### ISSUE THREAD

**Issue by brodsa** [brodsa/loopitoy#1]
As a **developer**
I want to **plan the development of the e-shop**
so that I can **smoothly develop the web page**

**ACCEPTANCE CRITERIA**
- [x] wireframes for mobile and desktop are created 
- [x] user stories are planned (acceptance criteria, tasks, MOSCOW)
- [x] colors, fonts, landing image are chosen
- [x] toys images are created
- [x] set up workspace

**TASKS**
- [x] design wireframes 
- [x] select colors, fonts, landing image
- [x] plan user stories
- [x] make a picture of toys
- [x] workspace is created
