### ISSUE TITLE
Toy Detail 

### ISSUE THREAD

**Issue by brodsa** [brodsa/loopitoy#10]
As a **Shopper**
I want to **view individual toys details**
so that I can **find the price, description, product image and quality**

**ACCEPTANCE CRITERIA**
- [x] each product is clickable from the toys page
- [x] product detail page contains some information
- [x] buttons to put in shopping bag or go back

**TASKS**
- [x] create detail product page
- [x] create buttons: put in shopping bag or go back button
