### ISSUE TITLE
Toy Groups

### ISSUE THREAD

**Issue by brodsa** [brodsa/loopitoy#11]
As a **Shopper**
I want to **quickly identify toys according to age group and toys categories**
so that I can **easily find appropriate toys for my children**

**ACCEPTANCE CRITERIA**
- [x] there is a menu item age group with age groups
- [x] there are toys categories in the menu dropdown item for all toys
- [x] the menu item redirects to the corresponding group

**TASKS**
- [x] create menu items which filters the toys according to the age
