### ISSUE TITLE
Bag Icon

### ISSUE THREAD

**Issue by brodsa** [brodsa/loopitoy#12]
As a **Shopper**
I want to **quickly see the total of my purchases at any time**
so that I can **avoid spending too much time**

**ACCEPTANCE CRITERIA**
- [x] total cost icon are in the header
- [x] correct total cost is displayed

**TASKS**
- [x] create bag icon
- [x] create logic to calculate total cost
