### ISSUE TITLE
Register Account

### ISSUE THREAD

**Issue by brodsa** [brodsa/loopitoy#13]
As a **Site User**
I want to **easily register**
so that I can **have a personal account**

**ACCEPTANCE CRITERIA**
- [x] allauth app is created and setup
- [x] there is a register page
- [x] there are buttons and menu item for register

**TASKS**
- [x] create allauth app
- [x] create register page
- [x] add buttons and links
