### ISSUE TITLE
Login & Logout

### ISSUE THREAD

**Issue by brodsa** [brodsa/loopitoy#14]
As a **Site User**
I want to **easily login and logout**
so that I can **access my account**

**ACCEPTANCE CRITERIA**
- [x] there are pages to login 
- [x] logout page
- [x] there are buttons and links to do so

**TASKS**
- [x] create login page
- [x] create logout page
- [x] add buttons and links
