### ISSUE TITLE
Recover Password

### ISSUE THREAD

**Issue by brodsa** [brodsa/loopitoy#15]
As a **Site User**
I want to **easily recover my password in case I forget it**
so that I can **recover access to my account**

**ACCEPTANCE CRITERIA**
- [x] there is a link to recover password
- [x] there is logic to do so

**TASKS**
- [x] create logic to recover password
- [x] add links to do so
