### ISSUE TITLE
Email Confirmation

### ISSUE THREAD

**Issue by brodsa** [brodsa/loopitoy#16]
As a **Site User**
I want to **receive an email confirmation after registering**
so that I can **verify that my account registration was successful**

**ACCEPTANCE CRITERIA**
- [x] there is a page which informs user about confirmation
- [x] user receives email with the corresponding text

**TASKS**
- [x] setup the email verification
- [x] create page to inform the user
- [x] create informative text
