### ISSUE TITLE
User Profile

### ISSUE THREAD

**Issue by brodsa** [brodsa/loopitoy#17]
As a **Site User**
I want to **capability**
so that I can **view/edit/ my personal information**

**ACCEPTANCE CRITERIA**
- [x] there is  a page with personal detail which I can update
- [x] only authorized user can view and update the personal information

**TASKS**
- [x] create a personal profile page for update
