### ISSUE TITLE
Sort all toys

### ISSUE THREAD

**Issue by brodsa** [brodsa/loopitoy#18]
As a **Shopper**
I want to **sort the list of available toys**
so that I can **easily identify the best priced toys, toys in the best quality and alphabetically sorted toys**

**ACCEPTANCE CRITERIA**
- [ ] the items in navigation menu works properly: by price, by quality, by name

**TASKS**
- [ ] modify the view logic for sorting and direction in get request
- [ ] add the url in navigation menu
