### ISSUE TITLE
Sort a specific toy category

### ISSUE THREAD

**Issue by brodsa** [brodsa/loopitoy#19]
As a **Shopper**
I want to **sort a specific and multiple category of products**
so that I can **easily find the toys for my kids.**

**ACCEPTANCE CRITERIA**
- [ ] there is select box to sort toys accordingly
- [ ] the selected choice works properly

**TASKS**
- [ ] create sort select boxy in navigation
- [ ] modify the view logic
- [ ] modify the template
