### ISSUE TITLE
Filter for toys categories

### ISSUE THREAD

**Issue by brodsa** [brodsa/loopitoy#20]
As a **Shopper**
I want to **filter for specific toys categories**
so that I can **easily find and see what I have searched for**

**ACCEPTANCE CRITERIA**
- [x] there are toys categories in navigation menu
- [x] the fully functional logic has been created
- [x] toy categories are displayed in the search bar

**TASKS**
- [x] add the items in the navigation menu
- [x] use category parameter to filter in template
- [x] modify the view logic
