### ISSUE TITLE
Search Toys

### ISSUE THREAD

**Issue by brodsa** [brodsa/loopitoy#21]
As a **Shopper**
I want to **search for toys by name or description**
so that I can **find a specific toy I would like to purchase**

**ACCEPTANCE CRITERIA**
- [x] there is a fully functional search input field
- [x] there is information on what have been searched/filtered for and number of results

**TASKS**
- [x] modify the view logic for get request using q
- [x] modify the template to see the number of results and searched term
