### ISSUE TITLE
Add to - Delete from Shopping Bag

### ISSUE THREAD

**Issue by brodsa** [brodsa/loopitoy#22]
As a **Shopper**
I want to **easily add/delete a toy when purchasing it**
so that I can **ensure that I select the correct product**

**ACCEPTANCE CRITERIA**
- [x] each toy page has button add
- [x] there is a button to delete a toy from  shopping bag that works
- [x] there is a toast after each addition into shopping bag

**TASKS**
- [x] create logic to add/delete the toy in the shopping bag
- [x] setup toast for shopping bag
