### ISSUE TITLE
View Shopping Bag

### ISSUE THREAD

**Issue by brodsa** [brodsa/loopitoy#23]
As a **Shopper**
I want to **view my shopping bag**
so that I can **identify the total cost of my purchase and all toys I will receive**

**ACCEPTANCE CRITERIA**
- [x] there is the app bag
- [x] there is shopping bag page
- [x] there are all listed toys to purchase
- [x] there is detail Information about total cost

**TASKS**
- [x] create bag app
- [x] create shopping bag page
- [x] add toy list, cost information to the page
- [x] create logic to calculate total cost
