### ISSUE TITLE
Save Delivery Info

### ISSUE THREAD

**Issue by brodsa** [brodsa/loopitoy#24]
As a **Shopper**
I want to **have the possibility to save my delivery information when checkout**
so that I do not **have to fill the information several times**

**ACCEPTANCE CRITERIA**
- [x] there is a check-box to save the information on the checkout page
- [x] there is a logic which works

**TASKS**

- [x] add the check-box
- [x] create the logic
