### ISSUE TITLE
Checkout 

### ISSUE THREAD

**Issue by brodsa** [brodsa/loopitoy#25]
As a **Shopper**
I want to **easily enter my payment information**
so that I can **checkout quickly and with no hassies**

**ACCEPTANCE CRITERIA**
- [x] there is a app created
- [x] the checkout page was created
- [x] there is a order overview
- [x] there is a form to fill delivery

**TASKS**
- [x] create checkout app
- [x] create the form to fill out delivery
- [x] add order overview
