### ISSUE TITLE
Stripe & Webhook

### ISSUE THREAD

**Issue by brodsa** [brodsa/loopitoy#26]
As a **Shopper**
I want to **feel my personal and payment Information is safe and secure**
so that I can **confidently provide the needed information to make a purchase**

**ACCEPTANCE CRITERIA**
- [x] stripe was setup on dev and prod
- [x] webhook was setup on dev and prod
- [x] the stripe and webhook credentials are hidden
- [x] payment input field is on checkout page

**TASKS**
- [x] setup webhook on dev and prod
- [x] setup stripe on dev and prod
- [x] add the credentials in heroku config var
- [x] add payment input filed on checkout page
