### ISSUE TITLE
Order Confirmation

### ISSUE THREAD

**Issue by brodsa** [brodsa/loopitoy#27]
As a **Shopper**
I want to **view an order confirmation after checkout**
so that I can **verify that I have not made any mistakes**

**ACCEPTANCE CRITERIA**
- [x] there is a order confirmation page after checkout
- [x] page contains order summary and delivery with billing info
- [x] there is a button to return to Homepage

**TASKS**
- [x] create an order confirmation page
- [x] add delivery and billing info
- [x] add button to go into homepage
