### ISSUE TITLE
Confirmation email after checkout 

### ISSUE THREAD

**Issue by brodsa** [brodsa/loopitoy#28]
As a **Shopper**
I want to **receive an email confirmation after checking out**
so that I can **keep the confirmation of what I have purchased for my records**

**ACCEPTANCE CRITERIA**
- [x] shopper gets confirmation email
- [x] email contains information about the order

**TASKS**
- [x] setup the email confirmation
- [x] prepare the text for email
