### ISSUE TITLE
Shopping History

### ISSUE THREAD

**Issue by brodsa** [brodsa/loopitoy#29]
As a **Shopper**
I want to **view shopping history**
so that I can **see what I have purchased so far**

**ACCEPTANCE CRITERIA**
- [x] in personal profile there is shopping history overview
- [x] each order can be view in details

**TASKS**
- [x] add shopping history
- [x] create a detail order page
