### ISSUE TITLE
Testing & Validation

### ISSUE THREAD

**Issue by brodsa** [brodsa/loopitoy#3]
As a **developer**
I want to **test and validate my webpage**
so that **guarantee full functionality and development according to best practice**

**ACCEPTANCE CRITERIA**
- [x] web page is validated 
- [x] web page is manually tested

**TASKS**
- [x] html validation
- [x] js validation
- [x] css validation
- [x] python validation
- [x] accessibility validation
- [x] Lighthouse validation
- [x] feature testing
- [x] user story testing
- [x] responsivnes testing
- [x] browser testing
