### ISSUE TITLE
Sell Toys

### ISSUE THREAD

**Issue by brodsa** [brodsa/loopitoy#30]
As a **Seller**
I want to **provide all information about toys**
so that Site Owner **can sell toys for me**

**ACCEPTANCE CRITERIA**
- [x] there is a page with the  form to sell a toy
- [x] the page includes instructions as well

**TASKS**
- [x] create page with the form
- [x] provide text for instructions
