### ISSUE TITLE
Selling History

### ISSUE THREAD

**Issue by brodsa** [brodsa/loopitoy#31]
As a **Seller**
I want to **see all sells in my user profile**
so that I can **view sell history and the status of each sell**

**ACCEPTANCE CRITERIA**
- [x] there is a sell history in the profile
- [x] each sell can be viewed additionally

**TASKS**
- [x] include the sell history in the user profile
- [x] create detail sell page
