### ISSUE TITLE
Request Money

### ISSUE THREAD

**Issue by brodsa** [brodsa/loopitoy#32]
As a **role**
I want to **capability**
so that I can **benefit**

**ACCEPTANCE CRITERIA**
- [x] there is a button to request money if the toy is sold
- [x] after request an confirmation is shown

**TASKS**
- [x] create confirmation page
- [x] create button
- [x] add links and url
