### ISSUE TITLE
Add a toy

### ISSUE THREAD

**Issue by brodsa** [brodsa/loopitoy#33]
As a **Store Owner**
I want to **add a toy**
so that I can **add new items to my store**

**ACCEPTANCE CRITERIA**
- [x] the app products/toys is setup
- [x] there is a page with form to add a new toy 
- [x] the page is visible only for store owner

**TASKS**
- [x] create app products
- [x] create a page with the form
- [x] secure the page for authentication for store owner
