### ISSUE TITLE
Update Toy Details

### ISSUE THREAD

**Issue by brodsa** [brodsa/loopitoy#34]
As a **Store Owner**
I want to **update toy details**
so that I can **change the information including toy status**

**ACCEPTANCE CRITERIA**
- [x] there is a page with the form to edit existing toys
- [x] there is a field to change the status - visible only for store owner
- [x] there is a link for each to to edit the information
- [x] the page can access only Site Owner

**TASKS**
- [x] create a page with the form
- [x] add the links in product overview page (maybe in a product detail page)
- [x] secure the page for authentication of the store owner
