### ISSUE TITLE
Delete a Toy

### ISSUE THREAD

**Issue by brodsa** [brodsa/loopitoy#35]
As a **Site Owner**
I want to **delete a toy**
so that I can **remove toys that are no longer for sale**

**ACCEPTANCE CRITERIA**
- [x] there is a way to delete toys from e-shop
- [x] there is a link to delete the to
- [x] only Site Owner can do that

**TASKS**
- [x] create logic to delete a toy
- [x] add the links to delete toys
- [x] authentication required
