### ISSUE TITLE
Hidden Pages

### ISSUE THREAD

**Issue by brodsa** [brodsa/loopitoy#36]
As a **Site User**
I want to **come back to home page in case I am unexpected request**
so that I can **continue purchasing**

**ACCEPTANCE CRITERIA**
- [x] hidden page 404 is created
- [x] hidden page 403 is created
- [x] hidden page 500 is created

**TASKS**
- [x] create hidden page 404
- [x] create hidden page 403
- [x] create hidden page 500
