### ISSUE TITLE
SEO Techniques

### ISSUE THREAD

**Issue by brodsa** [brodsa/loopitoy#37]
As a **Site Owner**
I want to **use some SEO techniques**
so that I can **increase the chance to purchase on my e-shop**

**ACCEPTANCE CRITERIA**
- [x] meta tags are fill out
- [x] sitemap is created
- [x] robots.txt is created

**TASKS**
- [x] fill out meta tags (keywords, description)
- [x] create sitemap
- [x] create robots.txt
