### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by brodsa** [brodsa/loopitoy#38]
As a **Site User**
I want to **see favicon in the browser tab**
so that I can **easily find the e-shop in my browser**

**ACCEPTANCE CRITERIA**
- [x] favicon is created
- [x] favicon is included

**TASKS**
- [x] create favicon
- [x] include favicon into the web page
