### ISSUE TITLE
Terms & Conditions

### ISSUE THREAD

**Issue by brodsa** [brodsa/loopitoy#39]
As a **Site User**
I want to **read about Terms and Conditions**
so that I  **know what to expect when selling toys**

**ACCEPTANCE CRITERIA**
- [x] Terms & Conditions are created
- [x] there is a link in footer

**TASKS**
- [x] create Terms & Conditions
- [x] create link in footer
