### ISSUE TITLE
Deployment

### ISSUE THREAD

**Issue by brodsa** [brodsa/loopitoy#4]
As a **developer**
I wan to  **deploy the page**
so that **guarantee that the web page is accessible to everyone**

**ACCEPTANCE CRITERIA**
- [x] web page is deployed on heroku
- [x] media and statics files are on S3
- [x] env.py is created with all credentials

**TASKS**
- [x] deploy on heroku
- [x] setup S3
- [x] create env.py and hide all credentials
