### ISSUE TITLE
Contact From

### ISSUE THREAD

**Issue by brodsa** [brodsa/loopitoy#40]
As a **User**
I want to **have the possibility to write the site owner**
so that I can **contact him/her in any matter**

**ACCEPTANCE CRITERIA**
- [x] contact app is created
- [x] contact form is created
- [x] thank you page is shown after sending the contact form

**TASKS**
- [x] create contact app
- [x] style and create contact form
- [x] create thank you page
