### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by brodsa** [brodsa/loopitoy#41]
As a **Site User**
I want to **have the possibility to provide review**
so that I can **support and make the e-shop more reliable**

**ACCEPTANCE CRITERIA**
- [x] review app is set up
- [x] form to provide review is created
- [x] page with all proved reviews is displayed

**TASKS**
- [x] review app
- [x] crate form
- [x] create page
