### ISSUE TITLE
Basic Info

### ISSUE THREAD

**Issue by brodsa** [brodsa/loopitoy#5]
As a **first visitor**
I want to **quickly see what the web-page offers**
so that I can **easily purchase or sell toys**

**ACCEPTANCE CRITERIA**
- [x] landing page is created with two buttons (shop now, sell toy)
- [x] header is created with logo and navigation menu
- [x] footer is created with social media links
- [x] how it works is created

**TASKS**
- [x] create header with logo and navigation menu
- [x] create footer
- [x] create landing page
- [x] create how it works page
- [x] test
- [x] documentation
