### ISSUE TITLE
Delivery & Refund Information

### ISSUE THREAD

**Issue by brodsa** [brodsa/loopitoy#6]
As a **Site User**
I want to **read delivery information**
so that I know **what to expect regarding delivery and refund**

**ACCEPTANCE CRITERIA**
- [x] delivery information page is created
- [x] link in footer
- [x] page contains delivery information and refund policy

**TASKS**
- [x] search for template 
- [x] create delivery information page
- [x] include info about refund
- [x] create link in footer
