### ISSUE TITLE
Privacy Policy

### ISSUE THREAD

**Issue by brodsa** [brodsa/loopitoy#7]
As a **role**
I want to **know how my date are used**
so that I can **decide which personal detail I provide**

**ACCEPTANCE CRITERIA**
- [x] privacy policy page is crated
- [x] page contains newsletter information
- [x] link in footer

**TASKS**
- [x] find template
- [x] create privacy policy page
- [x] add information about sending newsletter
- [x] create link in footer
