### ISSUE TITLE
Toys Overview

### ISSUE THREAD

**Issue by brodsa** [brodsa/loopitoy#9]
As a **Shopper**
I want to **view a list of all toys**
so that I can **see the whole e-shop offer and select some to purchase**

**ACCEPTANCE CRITERIA**
- [x] in navigation menu there is item to see all products
- [x] on the landing page there is a button to go to all product
- [x] each toy is on the web page represented by ist image
- [x] some information is provided
- [x] only toys with status for e-shop are displayed

**TASKS**
- [x] create toys card
- [x] provide short toy information
- [x] add links on landing page and in navigation menu
- [x] filter only toys for e-shop
- [x] test
- [x] documentation
